Fix Typescript Error: Update Case of Import File
Importing ImageUtilityService.d.ts in all lowercase is causing a typescript compilation error in the latest version. Matching cases resolve the issue.